<a href="https://colab.research.google.com/github/sosuke-p/kadai_003/blob/main/kadai_003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# step1 numpyの読み込み
import numpy as np

# step2 A,B行列の記述
A = np.array([[0, 1],[2, 3],[4,5]])
B = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])

# step3 行列の積計算
c = np.dot(A, B)

# step4 3の計算結果の表示
print(c)

# step5 最大値を求める
c.max()

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47